services:
  postgres:
    image: postgres:latest
    container_name: project-manager-4617-db-1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0704
      POSTGRES_DB: project_manager
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: